# ==============================================================================
#                 CI/CD Workflow: Build and Push States API
# ==============================================================================
#
# Workflow Name: A descriptive name for this specific automated process.
name: Build and Push States API Image

# This workflow triggers on every 'push' event to the 'main' branch.
on:
  push:
    branches: [ "main" ]

# --- CUSTOMIZABLE VARIABLES ---
env:
  # The name for your API's Docker image on Docker Hub.
  DOCKERHUB_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/states-api

# --- WORKFLOW JOBS ---
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Step 1: Checkout Repository Code'
        uses: actions/checkout@v4

      - name: 'Step 2: Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Step 3: Log in to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Step 4: Build, Tag, and Push Docker Image'
        uses: docker/build-push-action@v5
        with:
          # context is '.', meaning the root of the repository.
          context: .
          # The 'file:' line is removed, as Docker will automatically find
          # the 'Dockerfile' in the root of the context.
          push: true
          tags: ${{ env.DOCKERHUB_IMAGE_NAME }}:latest,${{ env.DOCKERHUB_IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKERHUB_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_IMAGE_NAME }}:buildcache,mode=max
