name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << EOF
            cd ~/states-api
            git fetch origin main
            git reset --hard origin/main
            echo "${{ secrets.DO_ENV_FILE }}" > .env

            # --- THE FINAL FIX ---
            # Forcefully remove the container by name if it exists to prevent conflicts.
            # The '|| true' ensures the script doesn't fail if the container isn't there.
            docker rm -f states-api || true

            # This will now correctly clean up the rest of the project
            docker compose down || true
            docker compose up --build -d
          EOF
